project:
  type: website

website:
  title: "IS415-GAA"
  
  page-footer: 
    center: "Copyright 2024, Low Jin Yuan" 
    right: 
      - icon: github
        href: https://github.com/dljyuan/IS415-GAA
    border: false
        
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01.html"
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_Ex02.html"
        
    right:
      - text: Home
        href: index.qmd
      - icon: github
        menu: 
          - text: Source Code
            url: "https://github.com/dljyuan/IS415-GAA"
          - text: Report a Bug
            url: "https://github.com/dljyuan/IS415-GAA"

format:
  html:
    theme: 
      light: [superhero, light.scss]
      dark: [superhero, dark.scss]
    css: styles.css
    toc: true

editor: visual

