---
title: "In-class Exercise 02: R for Geospatial Data Science"
execute: 
  eval: true
  echo: true
  warning: false
author: "Jin Yuan"
date: 01/15/2024
date-format: "DD/MM/YYYY"
editor: visual
categories:
  - In-class Exercise
title-block-categories: True
---

## Getting Started

**Preloading packages**

```{r}
pacman::p_load(arrow, lubridate, tidyverse, tmap, sf)
```

## Importing Grab-Posisi Dataset

```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show Code"
df <- arrow::read_parquet("/dljyuan/IS415-GAA/data/GrabPosisi/part-00000.parquet")
```

**Examination of Data Content**

```{r}
#| eval: false
View(df)
```

::: callout-note
**As the data for the timestamp is in integer not datetime, required conversion**
:::

```{r}
#| eval: false
df$pingtimestamp <- as_datetime(df$pingtimestamp)
```

## Converting into sf tibble

## Extracting trip starting locations

```{r}
#| eval: false
origin_df <- df %>%
  group_by(trj_id) %>%
  arrange(pingtimestamp) %>%
  filter(row_number()==1) %>%
  mutate(weekday = wday(pingtimestamp,
                        label=TRUE,
                        abbr=TRUE),
         start_hr = factor(hour(pingtimestamp)),
         day = factor(mday(pingtimestamp)))
```

## Extracting destination locations

```{r}
#| eval: false
destination_df <- df %>%
  group_by(trj_id) %>%
  arrange(desc(pingtimestamp)) %>%
  filter(row_number()==1) %>%
  mutate(weekday = wday(pingtimestamp,
                        label=TRUE,
                        abbr=TRUE),
         start_hr = factor(hour(pingtimestamp)),
         day = factor(mday(pingtimestamp)))
```

## Write data

```{r}
#| echo: false
#| eval: false
write_rds(origin_df, "/dljyuan/IS415-GAA/data/rds/origin_df.rds")
write_rds(destination_df, "/dljyuan/IS415-GAA/data/rds/destination_df.rds")
```

## Import data

```{r}
origin_df <- read_rds("/dljyuan/IS415-GAA/data/rds/origin_df.rds")
destination_df <- read_rds("/dljyuan/IS415-GAA/data/rds/destination_df.rds")
```
